ej1:
	g++ -std=c++11 -pthread Semaphore.cpp -c
	g++ -std=c++11 -pthread Semaphore.o ejercicio1.cpp -o ejercicio1

ej2:
	g++ -std=c++11 -pthread Semaphore.cpp -c
	g++ -std=c++11 -pthread Semaphore.o ejercicio2.cpp -o ejercicio2

ej3:
	g++ -std=c++11 -pthread Semaphore.cpp -c
	g++ -std=c++11 -pthread Semaphore.o ejercicio3.cpp -o ejercicio3
